/**
 * A structured request generated by the model.
 *
 * The ID connects this request to its eventual result. The name and arguments
 * are untrusted because the model—not application code—produced them.
 */
export interface ToolCall {
  id: string;
  name: string;
  arguments: unknown;
}

/**
 * A trusted tool implementation registered by the application.
 *
 * The description tells the model when the tool is useful. The execute
 * function remains inside the application and is never controlled by the model.
 */
export interface ToolDefinition {
  name: string;
  description: string;

  /**
   * Each tool validates its own input before performing any operation.
   */
  execute: (input: unknown) => Promise<unknown>;
}

/**
 * Tool metadata that is safe to expose without providing access to the
 * underlying executable function.
 */
export interface ToolSummary {
  name: string;
  description: string;
}

/**
 * A successful tool result.
 *
 * toolCallId preserves the connection between the model's request and this
 * result, which becomes important when multiple tools are called.
 */
export interface ToolSuccessResult {
  type: "tool_result";
  toolCallId: string;
  toolName: string;
  success: true;
  output: unknown;
}

/**
 * A failed tool result.
 *
 * Tool failures are represented as data so they can be logged, displayed,
 * and returned to the model without crashing the complete agent process.
 */
export interface ToolFailureResult {
  type: "tool_result";
  toolCallId: string;
  toolName: string;
  success: false;
  error: string;
}

/**
 * A discriminated union representing every possible tool outcome.
 *
 * Checking `success` tells TypeScript whether `output` or `error` is available.
 */
export type ToolResult = ToolSuccessResult | ToolFailureResult;
